language: node_js

node_js:
 - "7.7.0"
install:
  - npm install
  - npm install -g firebase-tools
script:
  - npm run build
deploy:
  - provider: firebase
  - token: $FIREBASE_TOKEN
# after_success:
#  - firebase deploy --token $FIREBASE_TOKEN
