language: node_js

node_js:
 - "7.7.0"
install:
  - npm install
  - npm install -g firebase-tools
script:
  - echo 'Testing something'
  - echo $REACT_APP_FIREBASE_API_KEY
  - npm run build
after_success:
 - firebase deploy --token $FIREBASE_TOKEN
